### ISSUE TITLE
Device disconnects mid-transfer

### ISSUE THREAD

**Issue by IceBotYT** [seemoo-lab/openwifipass#1]
I tried using this with an iPod touch running iOS 14.4, but this happened:
```
Start scanning...
SSID match in PWS advertisement from 61:48:a1:38:83:f5
Connect to device 61:48:a1:38:83:f5
Send PWS1
Receive PWS2
Send M1
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/openwifipass/__main__.py", line 31, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/openwifipass/__main__.py", line 27, in main
    startPWS(scanResult.addr, args.ssid, args.psk)
  File "/home/pi/.local/lib/python3.7/site-packages/openwifipass/Connection.py", line 117, in startPWS
    while peripheral.waitForNotifications(2):
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected
```

Can you help out? Thanks!

**Comment by schmittner** [comment]
I've never experienced this.

- what Pi model are you using?
- does this always happen?
- have you any other iOS/macOS devices that you can test with?

**Comment by IceBotYT** [comment]
I forget what model I'm using, but yeah this always happens. I do have plenty of other devices to try with too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by janniklorenz** [comment]
I've seen some disconnects during development after excessive testing, but a reboot of the iOS/macOS device fixed the issue at that time for me.

**Comment by IceBotYT** [comment]
Alright I'll try it later!
Unfortunately, a snow storm is headed my way so it may be delayed
________________________________
