### ISSUE TITLE
Python throw AttributeError

### ISSUE THREAD

**Issue by CharlesHe023** [seemoo-lab/openwifipass#5]
charles@xavier-nvme:~$ sudo -E python3 -m openwifipass --ssid MySSID --psk 'testpassword'
[sudo] password for charles: 
Start scanning...
SSID match in PWS advertisement from 5d:32:e4:bd:f0:3b
Connect to device 5d:32:e4:bd:f0:3b
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.6/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/charles/.local/lib/python3.6/site-packages/openwifipass/__main__.py", line 31, in <module>
    main()
  File "/home/charles/.local/lib/python3.6/site-packages/openwifipass/__main__.py", line 27, in main
    startPWS(scanResult.addr, args.ssid, args.psk)
  File "/home/charles/.local/lib/python3.6/site-packages/openwifipass/Connection.py", line 95, in startPWS
    grantorHandler = GrantorHandler(ssid, psk)
  File "/home/charles/.local/lib/python3.6/site-packages/openwifipass/GrantorHandler.py", line 17, in __init__
    self.session_keys = SessionKeys()
  File "/home/charles/.local/lib/python3.6/site-packages/openwifipass/Keys.py", line 9, in __init__
    encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
  File "/usr/lib/python3.6/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

**Comment by firkeuf** [comment]
You need to upgrade cryptography 
`pip3 install --upgrade cryptography`
